
<H1> PHP, Its Coarse And Rough And Irritating And it Gets Everywhere</h1>
<?php
$request_url = 'https://abcf6afb662f:5665/v1/objects/hosts';
$username = 'root';
$password = '8271facebe35bf55';
$headers = array(
    'Accept: application/json',
    'X-HTTP-Method-Override: GET'
);

$ch = curl_init();

curl_setopt_array($ch, array(

    CURLOPT_URL => $request_url,
    CURLOPT_HTTPHEADER => $headers,
    CURLOPT_USERPWD => $username . ":" . $password,
    CURLOPT_RETURNTRANSFER => true,
    // CURLOPT_CAINFO => "/etc/apache2/ssl/icinga2.cert",
    CURLOPT_SSL_VERIFYPEER => false,
));

$response = curl_exec($ch);

if($response === false){
    print "Error:" . curl_error($ch) . "(" . $response . ")\n";
}

$code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

print "Status: " . $code . "\n\n";
print "Response:" . var_dump(json_decode($response, true));

?> 

