<head>
</head>

<body>

<!-- <ul  id="dependency-menu"> -->
<!-- </ul> -->


<div class="column" id="dependency-network">
</div>

    <div id="loadingBar">
        <div class="outerBorder">
            <div id="text">0%</div>
            <!-- <div id="border"> -->
                <div id="bar"></div>
            <!-- </div> -->
        </div>
    </div>

 <div class="zoom">
  <a class="zoom-fab zoom-btn-large" id="zoomBtn">Edit</a>
  <ul class="zoom-menu">
    <li><a class="zoom-fab zoom-btn-sm zoom-btn-save scale-transition scale-out">Save</a></li>
  </ul>
</div>

</body>
