<div class="controls">
<?= $this->tabs ?>
</div>

<body>
    <div class="dependency-module-form">
        <h1>Dependency Module Settings</h1>
        <form class='settings-form'>
            <fieldset>
                <legend>Database Backend</legend>
                <dl>

                    <dt id="resource-label">Database Resource</dt>

                    <dd id="resource-element">
                        <select name="resource" id="resource-field">
                        </select>
                    </dd>

                </dl>
            </fieldset>
        </form>
        <form method="POST" class='settings-form'>
            <fieldset>
                <legend>API Login Information</legend>
                <dl>
                    <!-- <div class="hint"></div> -->
                    <dt id="host-label">
                        <label for="host">Host</label>
                    </dt>
                    <dd id="host-element">
                        <input type="text" name="host" id="host-field">
                    </dd>
                    <dt id="port-label">
                        <label for="port">Port</label>
                    </dt>
                    <dd id="port-element">
                        <input type="text" name="port" id="port-field">
                    </dd>

                    <dt id="username-label">
                        <label for="username">API User</label>
                    </dt>
                    <dd id="username-element">
                        <input type="text" name="username" , id='user-field'>
                    </dd>

                    <dt id="password-label">
                        <label for="password">Password</label>
                    </dt>
                    <dd id="password-element">
                        <input type="password" name="password" id='password-field'>
                    </dd>
                </dl>
                <dt id="button-label"></dt>
                <dd id="button-element">
                    <input type="submit">
                </dd>
            </fieldset>
        </form>
    </div>
</body>
<script>
if (document.readyState === "complete"){

       kickstartManager();

} else {
    window.onload = function () {

       kickstartManager();

    }
}
</script>
