<div class="controls">
    <?= $this->tabs ?>
</div>

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

    <!-- <ul  id="dependency-menu"> -->
    <!-- </ul> -->

    <div id="hud">
        <div class='hud-box' id='hud-title'></div>
        <div class='hud-box' id='hud-down'></div>
        <div class='hud-box' id='hud-unreachable'></div>
        <div class='hud-box' id='hud-up'></div>
    </div>
    <div class="column" id="dependency-network">
    </div>

    <div id="loadingBar">
        <div class="outerBorder">
            <div id="text">0%</div>
            <!-- <div id="border"> -->
            <div id="bar"></div>
            <!-- </div> -->
        </div>
    </div>

    <div class="fabs" id="edit-fabs">
        <a class="zoom-fab fab-btn-large" id="edit-btn">
            <i class="material-icons">mode_edit</i>
        </a>



        <ul class="fab-menu">
            <li>
                <a class="zoom-fab fab-btn-sm fab-btn-delete scale-transition scale-out">
                    <i class="material-icons">delete_forever</i>
                </a>
            </li>
            <li>
                <a class="zoom-fab fab-btn-sm fab-btn-save scale-transition scale-out">
                    <i class="material-icons">save</i>
                </a>
            </li>

            <li>
                <a class="zoom-fab fab-btn-sm fab-btn-dependency scale-transition scale-out">
                    <i class="material-icons">timeline</i>
                </a>

            </li>

            <li>
                <a class="zoom-fab fab-btn-sm fab-btn-fullscreen scale-transition scale-out">
                    <i class="material-icons">fullscreen</i>
                </a>

            </li>


        </ul>
    </div>


</body>
<script>
    if (document.readyState === "complete") {

        getRequests(false);

    } else {
        window.onload = function () {

            getRequests(false);

        }
    }
</script>